Function for generating 10 similar objects
htmlacademy-javascript/1452537-keksobooking-22 pull request #3
Opened 2021-02-10 14:25 UTC by Nikulichka

2021-02-11 07:21 UTC, Dima-Dim requested changes

2021-02-11 07:21 UTC, Dima-Dim commented on js/main.js
> +const TYPE = ['palace', 'flat', 'house', 'bungalow'];
Очень пространное название для константы и https://up.htmlacademy.ru/javascript/22/criteries#b5

2021-02-11 07:21 UTC, Dima-Dim commented on js/main.js
> +const FEATURES = ['wifi', 'dishwasher', 'parking', 'washer', 'elevator', 'conditioner'];
Уже лучше, но можно чуть добавить конкретики.

2021-02-11 07:21 UTC, Dima-Dim commented on js/main.js
> +  let shuffled = arr.slice(0), i = arr.length, min = i - count, temp, index;
В `shuffled` записыватся массив и далее в этой переменной всё так же остаётся тот же самый массив. Да, его состав меняется, но сам массив остаётся прежним. Так что похоже на const.

2021-02-11 07:21 UTC, Dima-Dim commented on js/main.js
> +      address: getRandomFloat(35.65000, 35.70000, 6).toString() + ', ' + getRandomFloat(139.70000, 139.80000, 6).toString(),
`35.65000, 35.70000, 6` - что за цифры? :) Магия!

2021-02-11 07:21 UTC, Dima-Dim commented on package.json
> +    "lodash": "^4.17.20",
Если устанавливаешь lodash в качестве зависимости, то добавлять ссылку на его cdn в index.html не нужно, его нужно импортировать в файлах, где он используется.

2021-02-11 09:52 UTC, Nikulichka commented on js/main.js
> +  let shuffled = arr.slice(0), i = arr.length, min = i - count, temp, index;
С const выдаёт ошибку: Uncaught SyntaxError: Missing initializer in const declaration

2021-02-11 11:08 UTC, Nikulichka commented on package.json
> +    "lodash": "^4.17.20",
А как импортировать? У меня не заработало, вот и добавила ссылку. Пробовала так: var _ = require('lodash'); и так: import _ from 'lodash';

2021-02-11 12:11 UTC, Dima-Dim commented on package.json
> +    "lodash": "^4.17.20",
`import _ from 'lodash';`
но я не вижу где ты его используешь.

2021-02-11 12:12 UTC, Dima-Dim commented on js/main.js
> +  let shuffled = arr.slice(0), i = arr.length, min = i - count, temp, index;
А вот по этому не нужно переменные через `,` объявлять.

2021-02-11 12:15 UTC, Dima-Dim commented on package.json
> +    "lodash": "^4.17.20",
Дальше `_.` и метод который тебе нужен :)

2021-02-13 06:32 UTC, Nikulichka commented
Доброго дня! Удалила зависимости lodash, подключила через CDN. lodash мне кажется очень удобным, поэтому я хотела его подключить. Или лучше пока не пользоваться lodash, а писать на чистом js? Как вы считаете?

2021-02-13 06:35 UTC, Dima-Dim commented
> Доброго дня! Удалила зависимости lodash, подключила через CDN. lodash мне кажется очень удобным, поэтому я хотела его подключить. Или лучше пока не пользоваться lodash, а писать на чистом js? Как вы считаете?

Привет! Т.к. мы тут только начинаем учить JS, то хорошо бы поучиться писать самой :) тем более что по программе у нас вроде нет уж совсем сложных моментов.

2021-02-13 06:51 UTC, Nikulichka commented
Ясненько, спасибо :) Если всё в порядке, можете закрыть ветку, вопросов больше нет.

2021-02-13 16:07 UTC, merged